### ISSUE TITLE
Safariで参加者一覧のところに隙間が空くことがある

### ISSUE THREAD

**Issue by furuya-s** [BLThunder1991/socketio-chat#1]
![chat](https://cloud.githubusercontent.com/assets/7775388/10875452/db65f220-8175-11e5-87ba-3c30ece107df.png)

こんな感じで隙間が空きます．
条件はわかりません．

**Comment by shuyuhey** [comment]
参加者一覧の表示方法が変わったので，このissueは発生しなくなったと思います．
