### ISSUE TITLE
提案：リアルタイムモード

### ISSUE THREAD

**Issue by ug23** [BLThunder1991/socketio-chat#10]
send.jsで行っている画面下端判定が自動スクロールしない原因みたい。

コンソールで `$("body").scrollTop($(".messages")[0].scrollHeight)` すれば
下端までスクロールするので定期的にこれを呼ぶだけで画面下端へスクロールできるのではないか

**Comment by shuyuhey** [comment]
ref #2 

了解．他のところで再現しないのは結構きついので，この方法で考えてみます．
