### ISSUE TITLE
投稿があったときに自動でスクロールしないことがある

### ISSUE THREAD

**Issue by shuyuhey** [BLThunder1991/socketio-chat#2]
1. 上にスクロール
2. ブラウザの機能を使って拡大
3. 下にスクロール

上記の手順だと，投稿があったときにスクロールされない．
スクロールバーが一番下にある状態で拡大すると，問題は発生しないらしい．

**Comment by shuyuhey** [comment]
色々試してみたけど，再現しないので，次問題が発生した時に原因を探る．

**Comment by furuya-s** [comment]
11/16現在も発生してますが，再現しません．

**Comment by ug23** [comment]
今日は `$("body").scrollTop($(".messages")[0].scrollHeight)` をsetIntervalで動かして対症療法しました

**Comment by shuyuhey** [comment]
リアルタイムモードで回避可能にしたのでclose
