### ISSUE TITLE
質問を終了する機能が欲しい

### ISSUE THREAD

**Issue by furuya-s** [BLThunder1991/socketio-chat#22]
質問が右上のポップアップに延々とスタックされているので、質問の回答を得られたらクローズできるようにしたい。

**Comment by furuya-s** [comment]
一つの案として、
本日に投稿された質問以外はスタックしないようにすれば一応延々と増え続けることはない。
根本的な解決にはならないけど、日をまたいで質問することはないので。

**Comment by shuyuhey** [comment]
あー，とりあえずそれが一番簡単な対応なのかな―．
